name: qrpay
description: >
  QRPay Merchant App offers a comprehensive solution for seamless receive money
  using QR codes, catering to Android and iOS platforms. Key features encompass
  effortless receive money through QR codes, a secure payment checkout page,
  versatile payment gateway integration, and an accessible Developer API.
  Welcome to the QRPay Payment Gateway Solutions Developer API Documentation.
  This comprehensive guide will empower you to seamlessly integrate our advanced
  payment gateway into your website, enhancing your customers’ payment experience
  and enabling efficient transaction processing. The QRPay Developer API is
  designed for developers and entrepreneurs who seek simplicity, security, and
  reliability in their payment processing solutions. Our commitment lies in
  delivering exceptional software solutions at a budget-friendly cost, empowering
  you to capitalize on opportunities and excel in this dynamic industry.
  Embrace the opportunity to elevate ordinary operations into extraordinary
  accomplishments with QRPay.

publish_to: "none"

version: 4.7.0+17

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # UI/UX
  flutter_screenutil: ^5.9.3
  google_fonts: 4.0.3
  pin_code_fields: ^8.0.1
  dotted_line: ^3.1.0
  flutter_svg:

  # Network and Connectivity
  http: ^0.13.5
  connectivity_plus: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_html: ^3.0.0-alpha.5
  share_plus:
  cached_network_image: ^3.2.3

  #Internationalization
  intl: ^0.18.0

  # Logging
  logger: ^2.3.0

  # Security
  local_auth: ^2.2.0

  # Country Information
  country_code_picker: 3.0.0

  # Image Handling
  image_picker: ^0.8.5+3

  # Drawing and Borders
  dotted_border: ^2.0.0+3
  iconsax: ^0.0.8
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.3.0
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.1.0
  pusher_beams: ^1.1.1
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.3.3
  flutter_gen_runner:

  # Code Quality
  dart_code_metrics: ^5.6.0

  flutter_launcher_icons: ^0.13.0
  change_app_package_name: ^1.1.0

  rename_app: ^1.6.1

dependency_overrides:
  archive: ^3.6.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_launcher.png"
  adaptive_icon_background: "#ffffff"  # Specify a background color or an image
  adaptive_icon_foreground: "assets/logo/app_launcher.png"  # Foreground image

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf
  assets:
    - assets/clipart/
    - assets/icon/
    - assets/icon/Paylink.svg
    - assets/logo/
    - assets/qr/
