// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7HVe8K6kERtSKsIU4du0K3Jx34xNQPw',
    appId: '1:363963407964:android:e60b44d13f7e3f60d0d099',
    messagingSenderId: '363963407964',
    projectId: 'waliifpay-dd5e6',
    databaseURL:
        'https://waliifpay-dd5e6-default-rtdb.firebaseio.com', // Add this if you have Firebase Realtime Database
    storageBucket: 'waliifpay-dd5e6.appspot.com',
    androidClientId:
        '363963407964-reonpbef0csjq7in8bt36lc118a0bp4f.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'YOUR_IOS_API_KEY', // Replace with actual API key for iOS from the plist
    appId: 'YOUR_IOS_APP_ID', // Replace with actual iOS app ID
    messagingSenderId: '363963407964',
    projectId: 'waliifpay-dd5e6',
    databaseURL: 'https://waliifpay-dd5e6-default-rtdb.firebaseio.com',
    storageBucket: 'waliifpay-dd5e6.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Replace with actual iOS client ID
    iosBundleId: 'YOUR_IOS_BUNDLE_ID', // Replace with actual iOS bundle ID
  );
}
